"""
Adversarial Debate Engine & Calibrated Log-Odds Fusion with Environmental Context Discounting.

Architectural Design:
    Implements a Prosecutor, Defender, and Judge triadic verification architecture
    for live biometric and acoustic streams. Specifically equips the Defender
    with domain rules that leverage environmental context flags (low-light, bitrate drop,
    stutter, multi-face) to discount false-positive biometric anomalies. Computes mathematically
    rigorous, calibrated log-odds Bayesian fusion.
"""

import math
from dataclasses import dataclass, field
from typing import List, Dict, Any, Tuple
from callguard.core.claim_adapter import Claim


@dataclass
class DebateArgument:
    role: str               # "prosecutor", "defender", "judge"
    text: str
    discount_applied: bool = False
    effective_weight: float = 1.0


@dataclass
class DebateResult:
    prior_probability: float
    posterior_probability: float
    log_odds: float
    confidence: float
    verdict: str            # "LIKELY SYNTHETIC", "UNCERTAIN", "CONSISTENT"
    transcript: List[DebateArgument]
    context_discounts_triggered: List[str]


class CallGuardDebateEngine:
    """
    Adversarial debate engine providing robust multi-modal biometric and forensic verification.
    """

    def __init__(
        self,
        prior_synthetic_prob: float = 0.10,
        low_light_discount: float = 0.25,
        bitrate_drop_discount: float = 0.30,
        stutter_discount: float = 0.30,
        multi_face_discount: float = 0.40,
    ):
        self.prior_p = prior_synthetic_prob
        # L0 = ln(P0 / (1 - P0))
        self.prior_log_odds = math.log(self.prior_p / (1.0 - self.prior_p))
        self.discounts = {
            "low_light": low_light_discount,
            "bitrate_drop": bitrate_drop_discount,
            "stutter": stutter_discount,
            "multi_face": multi_face_discount,
        }

    def debate_and_fuse(self, claims: List[Claim], ctx: Dict[str, Any], apply_context_discount: bool = True) -> DebateResult:
        """
        Executes adversarial debate between Prosecutor and Defender, followed by Judge Bayesian fusion.
        Args:
            claims: Polarized claims generated by ClaimAdapter.
            ctx: Environmental context flags (low_light, bitrate_drop, stutter, multi_face).
            apply_context_discount: If True, Defender discounts explained artifacts. (Ablation toggle).
        """
        transcript: List[DebateArgument] = []
        triggered_discounts: List[str] = []
        current_log_odds = self.prior_log_odds
        total_evidence_weight = 0.0

        # Step 1: Prior baseline
        transcript.append(DebateArgument(
            role="judge",
            text=f"Initial neutral prior: P(Synthetic)={self.prior_p:.2f} (Log-Odds={self.prior_log_odds:.3f})."
        ))

        # Step 2: Prosecutor & Defender debate each claim
        for claim in claims:
            base_w = claim.weight * claim.confidence
            effective_w = base_w
            discounted = False

            if claim.polarity == "synthetic":
                # PROSECUTOR: Argues manipulation based on anomaly
                p_text = f"PROSECUTION: {claim.text} (Severity weight: {base_w:.2f})"
                transcript.append(DebateArgument(role="prosecutor", text=p_text))

                # DEFENDER: Checks if any active ctx flag discounts this anomaly
                if apply_context_discount:
                    applicable_discounts = [flag for flag in claim.discountable_by if ctx.get(flag, False)]
                    if applicable_discounts:
                        # Combine discounts
                        discount_factor = 1.0
                        reasons = []
                        for flag in applicable_discounts:
                            d_val = self.discounts.get(flag, 0.5)
                            discount_factor *= d_val
                            reasons.append(f"{flag} (factor {d_val})")
                            triggered_discounts.append(f"{claim.claim_id}:{flag}")

                        effective_w = base_w * discount_factor
                        discounted = True
                        d_text = (
                            f"DEFENSE OBJECTION: Biometric anomaly is discounted due to active environmental "
                            f"context: {', '.join(reasons)}. Weight discounted from {base_w:.2f} down to {effective_w:.2f}."
                        )
                        transcript.append(DebateArgument(
                            role="defender", text=d_text, discount_applied=True, effective_weight=effective_w
                        ))
                    else:
                        d_text = f"DEFENSE: No environmental factor accounts for this anomaly. Admitting evidence."
                        transcript.append(DebateArgument(role="defender", text=d_text, effective_weight=effective_w))
                else:
                    d_text = f"DEFENSE (Ablation mode: discounting disabled): No discount applied."
                    transcript.append(DebateArgument(role="defender", text=d_text, effective_weight=effective_w))

                # Update log-odds towards synthetic
                current_log_odds += effective_w
                total_evidence_weight += effective_w

            elif claim.polarity == "authentic":
                # DEFENDER: Presents positive evidence of organic human physiology
                d_text = f"DEFENSE: {claim.text} (Authenticity weight: {base_w:.2f})"
                transcript.append(DebateArgument(role="defender", text=d_text, effective_weight=base_w))

                # PROSECUTOR: Cross-examines
                p_text = f"PROSECUTION: Cross-examined authentic observation (confidence {claim.confidence:.2f})."
                transcript.append(DebateArgument(role="prosecutor", text=p_text))

                # Update log-odds towards authentic (negative direction)
                current_log_odds -= effective_w
                total_evidence_weight += effective_w

        # Step 3: JUDGE Calibrated Posterior Log-Odds Fusion
        # P = 1 / (1 + exp(-L))
        # Guard against overflow
        clamped_log_odds = max(-20.0, min(20.0, current_log_odds))
        posterior_p = 1.0 / (1.0 + math.exp(-clamped_log_odds))
        
        # Overall confidence based on volume of accumulated evidence
        confidence = 1.0 - math.exp(-total_evidence_weight / 2.0)

        # Raw window verdict classification
        if posterior_p >= 0.70:
            raw_verdict = "LIKELY SYNTHETIC"
        elif posterior_p <= 0.30:
            raw_verdict = "CONSISTENT"
        else:
            raw_verdict = "UNCERTAIN"

        judge_verdict_text = (
            f"JUDGE VERDICT: Posterior Log-Odds={current_log_odds:.3f} -> Calibrated P(Synthetic)={posterior_p:.4f} "
            f"(Confidence={confidence:.2f}). Raw Window Verdict: {raw_verdict}."
        )
        transcript.append(DebateArgument(role="judge", text=judge_verdict_text))

        return DebateResult(
            prior_probability=self.prior_p,
            posterior_probability=posterior_p,
            log_odds=current_log_odds,
            confidence=confidence,
            verdict=raw_verdict,
            transcript=transcript,
            context_discounts_triggered=triggered_discounts,
        )
